name: OSV-Scanner Push/Scheduled Scan

on:
  # Nightly scheduled scan
  schedule:
    - cron: "0 1 * * *"

  # Run on all branches for every push
  push:

permissions:
  contents: read

jobs:
  osv-scan:
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.2.1
    with:
      scan-args: --recursive .
      upload-sarif: false
      fail-on-vuln: true