name: Publish NuGet

on:
  push:
    branches: [ main ]

  workflow_dispatch:

#defaults:
#  run:
#    working-directory: rzs-external--sieve

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: View
      run: |
        ls

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore

    - name: View
      run: |
        ls -R
            
#        dotnet nuget push "bin/Release/OctocatApp.1.0.0.nupkg"  --api-key YOUR_GITHUB_PAT --source "github"
