name: Publish NuGet

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Configure NuGet Auth
      run: |
        echo "NUGET_AUTH_TOKEN=${{ secrets.MACHINE_REPO_PAT }}" >> $GITHUB_ENV
        echo "Setting up NuGet source..."
        dotnet nuget add source https://nuget.pkg.github.com/room-zero-solutions/index.json --name GitHubRoomZero --username USERNAME --password $NUGET_AUTH_TOKEN --store-password-in-clear-text

    - name: View
      run: |
        ls

    - name: Restore dependencies
      run: dotnet restore 
    
    - name: Build
      run: dotnet build -c Release

    - name: View
      run: ls -R

    - name: Verify .nupkg File
      run: ls ./Sieve/bin/Release/*.nupkg

    - name: Publish
      run: dotnet nuget push ./Sieve/bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/room-zero-solutions/index.json --skip-duplicate
