name: Publish NuGet

on:
  push:
    branches: [ main ]

  workflow_dispatch:

#defaults:
#  run:
#    working-directory: rzs-external--sieve

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: View
      run: |
        ls

    - name: Restore dependencies
      run: dotnet restore 
    
    - name: Build
      run: dotnet build -c Release --no-restore

    #- name: View
    #  run: ls -R

    - name: Publish
      run: dotnet nuget push "./Sieve/bin/Release/RzsSieve.2.3.3.nupkg"  --api-key ${{ secrets.MACHINE_REPO_PAT }} --source "github"
